# Generated by Django 4.2.14 on 2024-08-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_program', models.CharField(max_length=2)),
                ('program_name', models.CharField(max_length=32)),
            ],
        ),
    ]
