# Generated by Django 4.2.14 on 2024-08-26 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystart', '0002_typeprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('code', models.ManyToManyField(related_name='programa', to='mystart.typeprogram')),
                ('userx', models.ManyToManyField(related_name='estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
