# Generated by Django 4.2.14 on 2024-08-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='versiculo',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
