# Generated by Django 4.2.14 on 2024-08-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_pregunta_versiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='versiculo',
            field=models.CharField(max_length=7),
        ),
    ]
